### ISSUE TITLE
求教：这段代码怎么理解？

### ISSUE THREAD

**Issue by weidongzhou1994** [Python3WebSpider/ScrapeStatic1#2]
published_at = re.search('(\d{4}-\d{2}-\d{2})', published_at).group(1) \
        if published_at and re.search('\d{4}-\d{2}-\d{2}', published_at) else None

**Comment by Germey** [comment]
查找是否有符合这个正则表达式的结果，如果有，就提取出来，否则就是 None，这个正则表达式是匹配四个数字加横线加两个数字加横线再加两个数字，就比如 2020-02-12，就是日期格式。
